version: '2'
services:
  plex:
    image: linuxserver/plex
    volumes:
      # - ./plex/config:/config 
      - ./plex/media/tv:/data/tvshows 
      - ./plex/media/movies:/data/movies 
      - ./plex/transcode:/transcode
      - ./deluge/downloads:/data/downloads 
    ports:
      - "32400:32400"
      - "32400:32400/udp"
      - "32469:32469"
      - "32469:32469/udp" 
      - "5353:5353/udp" 
      - "1900:1900/udp"
    network_mode: host
    environment:
      - VERSION=latest
  deluge:
      image: linuxserver/deluge
      container_name: deluge
      network_mode: host
      environment:
        - PUID=1001
        - PGID=1001
        - UMASK_SET=<022>
        - TZ=<timezone>
      volumes:
        - ./deluge/downloads:/config
        - ./deluge/downloads:/downloads
# ssh -L 32400:localhost:32400 server1